[package]
name = "solana-client"
version = "1.9.17"
description = "Solana Client"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-client"
license = "Apache-2.0"
edition = "2021"

[dependencies]
base64 = "0.13.0"
bincode = "1.3.3"
bs58 = "0.4.0"
<<<<<<< HEAD
clap = "2.33.0"
=======
bytes = "1.1.0"
clap = "3.1.8"
crossbeam-channel = "0.5"
futures = "0.3"
futures-util = "0.3.21"
>>>>>>> 9db7104e4 (chore: bump clap from 2.33.3 to 3.1.8 (#206))
indicatif = "0.16.2"
jsonrpc-core = "18.0.0"
log = "0.4.14"
<<<<<<< HEAD
rayon = "1.5.1"
reqwest = { version = "0.11.6", default-features = false, features = ["blocking", "rustls-tls", "json"] }
semver = "1.0.4"
serde = "1.0.130"
=======
lru = "0.7.5"
quinn = "0.8.2"
quinn-proto = "0.8.0"
rand = "0.8.5"
rand_chacha = "0.2.2"
rayon = "1.5.2"
reqwest = { version = "0.11.10", default-features = false, features = ["blocking", "rustls-tls", "json"] }
rustls = { version = "0.20.2", features = ["dangerous_configuration"] }
semver = "1.0.7"
serde = "1.0.136"
>>>>>>> 318544455 (chore: bump rand from 0.7.3 to 0.8.5 (#205))
serde_derive = "1.0.103"
serde_json = "1.0.72"
solana-account-decoder = { path = "../account-decoder", version = "=1.9.17" }
solana-clap-utils = { path = "../clap-utils", version = "=1.9.17" }
solana-faucet = { path = "../faucet", version = "=1.9.17" }
solana-net-utils = { path = "../net-utils", version = "=1.9.17" }
solana-measure = { path = "../measure", version = "=1.9.17" }
solana-sdk = { path = "../sdk", version = "=1.9.17" }
solana-transaction-status = { path = "../transaction-status", version = "=1.9.17" }
solana-version = { path = "../version", version = "=1.9.17" }
solana-vote-program = { path = "../programs/vote", version = "=1.9.17" }
thiserror = "1.0"
tokio = { version = "1", features = ["full"] }
tungstenite = { version = "0.16.0", features = ["rustls-tls-webpki-roots"] }
url = "2.2.2"

[dev-dependencies]
assert_matches = "1.5.0"
jsonrpc-http-server = "18.0.0"
solana-logger = { path = "../logger", version = "=1.9.17" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
