[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2021"
name = "solana-sys-tuner"
description = "The solana cluster system tuner daemon"
version = "1.9.17"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-sys-tuner"
publish = true

[dependencies]
<<<<<<< HEAD
<<<<<<< HEAD
clap = "2.33.1"
=======
=======
>>>>>>> 0d773bd13 (chore: bump tokio-util from 0.6.9 to 0.7.1 (#213))
clap = "3.1.8"
libc = "0.2.120"
>>>>>>> 9db7104e4 (chore: bump clap from 2.33.3 to 3.1.8 (#206))
log = "0.4.14"
libc = "0.2.108"
solana-logger = { path = "../logger", version = "=1.9.17" }
solana-version = { path = "../version", version = "=1.9.17" }

[target."cfg(unix)".dependencies]
unix_socket2 = "0.5.4"
users = "0.10.0"
nix = "0.23.0"
sysctl = "0.4.3"

[lib]
name = "solana_sys_tuner"

[[bin]]
name = "solana-sys-tuner"
path = "src/main.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
