[package]
name = "solana-cargo-build-bpf"
version = "1.9.17"
description = "Compile a local package and all of its dependencies using the Solana BPF SDK"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana"
homepage = "https://solana.com/"
license = "Apache-2.0"
edition = "2021"
publish = false

[dependencies]
bzip2 = "0.4.3"
<<<<<<< HEAD
clap = "2.33.3"
=======
cargo_metadata = "0.14.2"
clap = { version = "3.1.8", features = ["cargo", "env"] }
<<<<<<< HEAD
>>>>>>> 9db7104e4 (chore: bump clap from 2.33.3 to 3.1.8 (#206))
=======
>>>>>>> 0d773bd13 (chore: bump tokio-util from 0.6.9 to 0.7.1 (#213))
regex = "1.5.4"
cargo_metadata = "0.14.1"
solana-sdk = { path = "..", version = "=1.9.17" }
solana-download-utils = { path = "../../download-utils", version = "=1.9.17" }
tar = "0.4.37"

[dev-dependencies]
serial_test = "*"

[features]
program = []

[[bin]]
name = "cargo-build-bpf"
path = "src/main.rs"
