[package]
name = "solana-ed25519-program-tests"
version = "1.9.17"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
edition = "2021"
publish = false

[dev-dependencies]
assert_matches = "1.5.0"
ed25519-dalek = "=1.0.1"
<<<<<<< HEAD
<<<<<<< HEAD
rand = "0.7.0"
solana-program-test = { path = "../../program-test", version = "=1.9.17" }
solana-sdk = { path = "../../sdk", version = "=1.9.17" }
=======
=======
>>>>>>> 0d773bd13 (chore: bump tokio-util from 0.6.9 to 0.7.1 (#213))
rand = "0.8.5"
solana-program-test = { path = "../../program-test", version = "=1.11.0" }
solana-sdk = { path = "../../sdk", version = "=1.11.0" }
>>>>>>> 318544455 (chore: bump rand from 0.7.3 to 0.8.5 (#205))

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
