[package]
name = "solana-bpf-loader-program"
version = "1.9.17"
description = "Solana BPF loader"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-bpf-loader-program"
edition = "2021"

[dependencies]
bincode = "1.3.3"
byteorder = "1.4.3"
log = "0.4.14"
libsecp256k1 = "0.6.0"
solana-measure = { path = "../../measure", version = "=1.9.17" }
solana-metrics = { path = "../../metrics", version = "=1.9.17" }
solana-program-runtime = { path = "../../program-runtime", version = "=1.9.17" }
solana-sdk = { path = "../../sdk", version = "=1.9.17" }
solana_rbpf = "=0.2.24"
thiserror = "1.0"

[dev-dependencies]
<<<<<<< HEAD
<<<<<<< HEAD
rand = "0.7.3"
solana-runtime = { path = "../../runtime", version = "=1.9.17" }
=======
=======
>>>>>>> 0d773bd13 (chore: bump tokio-util from 0.6.9 to 0.7.1 (#213))
rand = "0.8.5"
solana-runtime = { path = "../../runtime", version = "=1.11.0" }
>>>>>>> 318544455 (chore: bump rand from 0.7.3 to 0.8.5 (#205))

[lib]
crate-type = ["lib"]
name = "solana_bpf_loader_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
