# Validate your changes with:
#
#   $ curl -F 'data=@.mergify.yml' https://gh.mergify.io/validate/
#
# https://doc.mergify.io/
pull_request_rules:
  - name: automatic merge (squash) on CI success
    conditions:
      - and:
        - label=automerge
        - label!=no-automerge
    actions:
      merge:
        method: squash
  - name: remove outdated reviews
    conditions:
      - base=master
    actions:
      dismiss_reviews:
        changes_requested: true
  - name: v1.9 feature-gate backportb
    conditions:
      - label=v1.9
      - label=feature-gate
    actions:
      backport:
        assignees:
          - "{{ merged_by|replace('mergify[bot]', label|select('equalto', 'community')|first|default(author)|replace('community', '')) }}"
        ignore_conflicts: true
        labels:
          - feature-gate
        branches:
          - v1.9
  - name: v1.9 non-feature-gate backport
    conditions:
      - label=v1.9
      - label!=feature-gate
    actions:
      backport:
        assignees:
          - "{{ merged_by|replace('mergify[bot]', label|select('equalto', 'community')|first|default(author)|replace('community', '')) }}"
        ignore_conflicts: true
        branches:
          - v1.9
  - name: v1.10 feature-gate backport
    conditions:
      - label=v1.10
      - label=feature-gate
    actions:
      backport:
        assignees:
          - "{{ merged_by|replace('mergify[bot]', label|select('equalto', 'community')|first|default(author)|replace('community', '')) }}"
        ignore_conflicts: true
        labels:
          - feature-gate
        branches:
          - v1.10
  - name: v1.10 non-feature-gate backport
    conditions:
      - label=v1.10
      - label!=feature-gate
    actions:
      backport:
        assignees:
          - "{{ merged_by|replace('mergify[bot]', label|select('equalto', 'community')|first|default(author)|replace('community', '')) }}"
        ignore_conflicts: true
        branches:
          - v1.10
