os: linux
dist: bionic
language: minimal

jobs:
  include:
    # explorer pull request
    - name: "explorer"
      if: type = pull_request AND branch = master

      language: node_js
      node_js:
        - "node"

      cache:
        directories:
          - ~/.npm

      before_install:
        - cd explorer

      script:
        - npm run build
        - npm run format