[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2021"
name = "solana-transaction-dos"
version = "1.9.17"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
publish = false

[dependencies]
bincode = "1.3.3"
clap = "3.1.8"
log = "0.4.14"
<<<<<<< HEAD
<<<<<<< HEAD
rand = "0.7.0"
rayon = "1.5.1"
solana-cli = { path = "../cli", version = "=1.9.17" }
solana-clap-utils = { path = "../clap-utils", version = "=1.9.17" }
solana-client = { path = "../client", version = "=1.9.17" }
solana-core = { path = "../core", version = "=1.9.17" }
solana-faucet = { path = "../faucet", version = "=1.9.17" }
solana-gossip = { path = "../gossip", version = "=1.9.17" }
solana-logger = { path = "../logger", version = "=1.9.17" }
solana-measure = { path = "../measure", version = "=1.9.17" }
solana-net-utils = { path = "../net-utils", version = "=1.9.17" }
solana-runtime = { path = "../runtime", version = "=1.9.17" }
solana-sdk = { path = "../sdk", version = "=1.9.17" }
solana-streamer = { path = "../streamer", version = "=1.9.17" }
solana-transaction-status = { path = "../transaction-status", version = "=1.9.17" }
solana-version = { path = "../version", version = "=1.9.17" }
=======
=======
>>>>>>> 0d773bd13 (chore: bump tokio-util from 0.6.9 to 0.7.1 (#213))
rand = "0.8.5"
rayon = "1.5.2"
solana-clap-utils = { path = "../clap-utils", version = "=1.11.0" }
solana-cli = { path = "../cli", version = "=1.11.0" }
solana-client = { path = "../client", version = "=1.11.0" }
solana-core = { path = "../core", version = "=1.11.0" }
solana-faucet = { path = "../faucet", version = "=1.11.0" }
solana-gossip = { path = "../gossip", version = "=1.11.0" }
solana-logger = { path = "../logger", version = "=1.11.0" }
solana-measure = { path = "../measure", version = "=1.11.0" }
solana-net-utils = { path = "../net-utils", version = "=1.11.0" }
solana-runtime = { path = "../runtime", version = "=1.11.0" }
solana-sdk = { path = "../sdk", version = "=1.11.0" }
solana-streamer = { path = "../streamer", version = "=1.11.0" }
solana-transaction-status = { path = "../transaction-status", version = "=1.11.0" }
solana-version = { path = "../version", version = "=1.11.0" }
>>>>>>> 318544455 (chore: bump rand from 0.7.3 to 0.8.5 (#205))

[dev-dependencies]
solana-local-cluster = { path = "../local-cluster", version = "=1.9.17" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
