[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2021"
name = "solana-genesis"
description = "Blockchain, Rebuilt for Scale"
version = "1.9.17"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-genesis"

[dependencies]
<<<<<<< HEAD
<<<<<<< HEAD
base64 = "0.12.3"
clap = "2.33.1"
serde = "1.0.130"
serde_json = "1.0.72"
serde_yaml = "0.8.21"
solana-clap-utils = { path = "../clap-utils", version = "=1.9.17" }
solana-cli-config = { path = "../cli-config", version = "=1.9.17" }
solana-entry = { path = "../entry", version = "=1.9.17" }
solana-ledger = { path = "../ledger", version = "=1.9.17" }
solana-logger = { path = "../logger", version = "=1.9.17" }
solana-runtime = { path = "../runtime", version = "=1.9.17" }
solana-sdk = { path = "../sdk", version = "=1.9.17" }
solana-stake-program = { path = "../programs/stake", version = "=1.9.17" }
solana-version = { path = "../version", version = "=1.9.17" }
solana-vote-program = { path = "../programs/vote", version = "=1.9.17" }
tempfile = "3.2.0"
=======
=======
>>>>>>> 0d773bd13 (chore: bump tokio-util from 0.6.9 to 0.7.1 (#213))
base64 = "0.13.0"
clap = "3.1.8"
serde = "1.0.136"
serde_json = "1.0.79"
serde_yaml = "0.8.23"
solana-clap-utils = { path = "../clap-utils", version = "=1.11.0" }
solana-cli-config = { path = "../cli-config", version = "=1.11.0" }
solana-entry = { path = "../entry", version = "=1.11.0" }
solana-ledger = { path = "../ledger", version = "=1.11.0" }
solana-logger = { path = "../logger", version = "=1.11.0" }
solana-runtime = { path = "../runtime", version = "=1.11.0" }
solana-sdk = { path = "../sdk", version = "=1.11.0" }
solana-stake-program = { path = "../programs/stake", version = "=1.11.0" }
solana-version = { path = "../version", version = "=1.11.0" }
solana-vote-program = { path = "../programs/vote", version = "=1.11.0" }
tempfile = "3.3.0"
>>>>>>> 9db7104e4 (chore: bump clap from 2.33.3 to 3.1.8 (#206))

[[bin]]
name = "solana-genesis"
path = "src/main.rs"

[lib]
name = "solana_genesis"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
