[package]
name = "solana-stake-accounts"
description = "Blockchain, Rebuilt for Scale"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2021"
version = "1.9.17"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-stake-accounts"

[dependencies]
<<<<<<< HEAD
<<<<<<< HEAD
clap = "2.33.1"
solana-clap-utils = { path = "../clap-utils", version = "=1.9.17" }
solana-cli-config = { path = "../cli-config", version = "=1.9.17" }
solana-client = { path = "../client", version = "=1.9.17" }
solana-remote-wallet = { path = "../remote-wallet", version = "=1.9.17" }
solana-sdk = { path = "../sdk", version = "=1.9.17" }
solana-stake-program = { path = "../programs/stake", version = "=1.9.17" }
=======
=======
>>>>>>> 0d773bd13 (chore: bump tokio-util from 0.6.9 to 0.7.1 (#213))
clap = "3.1.8"
solana-clap-utils = { path = "../clap-utils", version = "=1.11.0" }
solana-cli-config = { path = "../cli-config", version = "=1.11.0" }
solana-client = { path = "../client", version = "=1.11.0" }
solana-remote-wallet = { path = "../remote-wallet", version = "=1.11.0" }
solana-sdk = { path = "../sdk", version = "=1.11.0" }
solana-stake-program = { path = "../programs/stake", version = "=1.11.0" }
>>>>>>> 9db7104e4 (chore: bump clap from 2.33.3 to 3.1.8 (#206))

[dev-dependencies]
solana-runtime = { path = "../runtime", version = "=1.9.17" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
