[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2021"
name = "solana-watchtower"
description = "Blockchain, Rebuilt for Scale"
version = "1.9.17"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-watchtower"

[dependencies]
<<<<<<< HEAD
<<<<<<< HEAD
clap = "2.33.1"
=======
clap = "3.1.8"
=======
clap = "3.1.10"
>>>>>>> e39c48ccd (chore: bump clap from 3.1.8 to 3.1.10 (#211))
humantime = "2.0.1"
>>>>>>> 9db7104e4 (chore: bump clap from 2.33.3 to 3.1.8 (#206))
log = "0.4.14"
humantime = "2.0.1"
solana-clap-utils = { path = "../clap-utils", version = "=1.9.17" }
solana-cli-config = { path = "../cli-config", version = "=1.9.17" }
solana-cli-output = { path = "../cli-output", version = "=1.9.17" }
solana-client = { path = "../client", version = "=1.9.17" }
solana-logger = { path = "../logger", version = "=1.9.17" }
solana-metrics = { path = "../metrics", version = "=1.9.17" }
solana-notifier = { path = "../notifier", version = "=1.9.17" }
solana-sdk = { path = "../sdk", version = "=1.9.17" }
solana-version = { path = "../version", version = "=1.9.17" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
