[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2021"
name = "solana-poh-bench"
version = "1.9.17"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-poh-bench"
publish = false

[dependencies]
<<<<<<< HEAD
clap = "2.33.1"
=======
clap = { version = "3.1.8", features = ["cargo"] }
>>>>>>> 9db7104e4 (chore: bump clap from 2.33.3 to 3.1.8 (#206))
log = "0.4.14"
rand = "0.7.0"
rayon = "1.5.1"
solana-logger = { path = "../logger", version = "=1.9.17" }
solana-entry = { path = "../entry", version = "=1.9.17" }
solana-sdk = { path = "../sdk", version = "=1.9.17" }
solana-measure = { path = "../measure", version = "=1.9.17" }
solana-version = { path = "../version", version = "=1.9.17" }
solana-perf = { path = "../perf", version = "=1.9.17" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
