[package]
name = "rbpf-cli"
version = "1.9.17"
description = "CLI to test and analyze eBPF programs"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/rbpf"
homepage = "https://solana.com/"
keywords = ["BPF", "eBPF", "interpreter", "JIT"]
edition = "2021"
publish = false

[dependencies]
<<<<<<< HEAD
<<<<<<< HEAD
clap = "3.0.0-beta.2"
serde = "1.0.130"
serde_json = "1.0.72"
solana-bpf-loader-program = { path = "../programs/bpf_loader", version = "=1.9.17" }
solana-logger = { path = "../logger", version = "=1.9.17" }
solana-program-runtime = { path = "../program-runtime", version = "=1.9.17" }
solana-sdk = { path = "../sdk", version = "=1.9.17" }
solana_rbpf = "=0.2.24"
time = "0.3.5"
=======
clap = { version = "3.1.8", features = ["cargo"] }
=======
clap = { version = "3.1.10", features = ["cargo"] }
>>>>>>> e39c48ccd (chore: bump clap from 3.1.8 to 3.1.10 (#211))
serde = "1.0.136"
serde_json = "1.0.79"
solana-bpf-loader-program = { path = "../programs/bpf_loader", version = "=1.11.0" }
solana-logger = { path = "../logger", version = "=1.11.0" }
solana-program-runtime = { path = "../program-runtime", version = "=1.11.0" }
solana-sdk = { path = "../sdk", version = "=1.11.0" }
solana_rbpf = "=0.2.25"
>>>>>>> 9db7104e4 (chore: bump clap from 2.33.3 to 3.1.8 (#206))
