[package]
name = "solana-bucket-map"
version = "1.9.17"
description = "solana-bucket-map"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-bucket-map"
readme = "../README.md"
repository = "https://github.com/solana-labs/solana"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
license = "Apache-2.0"
edition = "2021"

[dependencies]
rayon = "1.5.0"
solana-logger = { path = "../logger", version = "=1.9.17" }
solana-sdk = { path = "../sdk", version = "=1.9.17" }
memmap2 = "0.5.0"
log = { version = "0.4.11" }
<<<<<<< HEAD
solana-measure = { path = "../measure", version = "=1.9.17" }
rand = "0.7.0"
=======
memmap2 = "0.5.3"
modular-bitfield = "0.11.2"
rand = "0.8.5"
solana-measure = { path = "../measure", version = "=1.11.0" }
solana-sdk = { path = "../sdk", version = "=1.11.0" }
tempfile = "3.3.0"

[dev-dependencies]
>>>>>>> 318544455 (chore: bump rand from 0.7.3 to 0.8.5 (#205))
fs_extra = "1.2.0"
tempfile = "3.2.0"

[lib]
crate-type = ["lib"]
name = "solana_bucket_map"

[[bench]]
name = "bucket_map"
