[package]
name = "solana-cargo-test-bpf"
version = "1.9.17"
description = "Execute all unit and integration tests after building with the Solana BPF SDK"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana"
homepage = "https://solana.com/"
license = "Apache-2.0"
edition = "2021"
publish = false

[dependencies]
<<<<<<< HEAD
clap = "2.33.3"
cargo_metadata = "0.14.1"
=======
cargo_metadata = "0.14.2"
<<<<<<< HEAD
clap = { version = "3.1.8", features = ["cargo"] }
>>>>>>> 9db7104e4 (chore: bump clap from 2.33.3 to 3.1.8 (#206))
=======
clap = { version = "3.1.10", features = ["cargo"] }
>>>>>>> e39c48ccd (chore: bump clap from 3.1.8 to 3.1.10 (#211))

[[bin]]
name = "cargo-test-bpf"
path = "src/main.rs"
