[package]
name = "solana-net-utils"
version = "1.9.17"
description = "Solana Network Utilities"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-net-utils"
edition = "2021"

[dependencies]
bincode = "1.3.3"
<<<<<<< HEAD
<<<<<<< HEAD
clap = "2.33.1"
=======
=======
>>>>>>> 0d773bd13 (chore: bump tokio-util from 0.6.9 to 0.7.1 (#213))
clap = { version = "3.1.8", features = ["cargo"] }
crossbeam-channel = "0.5"
>>>>>>> 9db7104e4 (chore: bump clap from 2.33.3 to 3.1.8 (#206))
log = "0.4.14"
<<<<<<< HEAD
<<<<<<< HEAD
nix = "0.23.0"
rand = "0.7.0"
serde = "1.0.130"
=======
=======
>>>>>>> 0d773bd13 (chore: bump tokio-util from 0.6.9 to 0.7.1 (#213))
nix = "0.23.1"
rand = "0.8.5"
serde = "1.0.136"
>>>>>>> 318544455 (chore: bump rand from 0.7.3 to 0.8.5 (#205))
serde_derive = "1.0.103"
socket2 = "0.4.2"
solana-logger = { path = "../logger", version = "=1.9.17" }
solana-sdk = { path = "../sdk", version = "=1.9.17" }
solana-version = { path = "../version", version = "=1.9.17" }
tokio = { version = "1", features = ["full"] }
url = "2.2.2"

[lib]
name = "solana_net_utils"

[[bin]]
name = "solana-ip-address"
path = "src/bin/ip_address.rs"

[[bin]]
name = "solana-ip-address-server"
path = "src/bin/ip_address_server.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
