[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2021"
name = "solana-banking-bench"
version = "1.9.17"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
publish = false

[dependencies]
<<<<<<< HEAD
clap = "2.33.1"
=======
clap = { version = "3.1.10", features = ["derive"] }
>>>>>>> e39c48ccd (chore: bump clap from 3.1.8 to 3.1.10 (#211))
crossbeam-channel = "0.5"
log = "0.4.14"
<<<<<<< HEAD
rand = "0.7.0"
rayon = "1.5.1"
solana-core = { path = "../core", version = "=1.9.17" }
solana-gossip = { path = "../gossip", version = "=1.9.17" }
solana-ledger = { path = "../ledger", version = "=1.9.17" }
solana-logger = { path = "../logger", version = "=1.9.17" }
solana-measure = { path = "../measure", version = "=1.9.17" }
solana-perf = { path = "../perf", version = "=1.9.17" }
solana-poh = { path = "../poh", version = "=1.9.17" }
solana-runtime = { path = "../runtime", version = "=1.9.17" }
solana-streamer = { path = "../streamer", version = "=1.9.17" }
solana-sdk = { path = "../sdk", version = "=1.9.17" }
solana-version = { path = "../version", version = "=1.9.17" }
=======
rand = "0.8.5"
rayon = "1.5.2"
solana-core = { path = "../core", version = "=1.11.0" }
solana-gossip = { path = "../gossip", version = "=1.11.0" }
solana-ledger = { path = "../ledger", version = "=1.11.0" }
solana-logger = { path = "../logger", version = "=1.11.0" }
solana-measure = { path = "../measure", version = "=1.11.0" }
solana-perf = { path = "../perf", version = "=1.11.0" }
solana-poh = { path = "../poh", version = "=1.11.0" }
solana-runtime = { path = "../runtime", version = "=1.11.0" }
solana-sdk = { path = "../sdk", version = "=1.11.0" }
solana-streamer = { path = "../streamer", version = "=1.11.0" }
solana-version = { path = "../version", version = "=1.11.0" }
>>>>>>> 318544455 (chore: bump rand from 0.7.3 to 0.8.5 (#205))

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
