[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2021"
name = "solana-dos"
version = "1.9.17"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
publish = false

[dependencies]
bincode = "1.3.3"
<<<<<<< HEAD
<<<<<<< HEAD
clap = "2.33.1"
=======
clap = {version = "3.1.8", features = ["derive", "cargo"]}
>>>>>>> 9db7104e4 (chore: bump clap from 2.33.3 to 3.1.8 (#206))
log = "0.4.14"
<<<<<<< HEAD
rand = "0.7.0"
solana-core = { path = "../core", version = "=1.9.17" }
solana-gossip = { path = "../gossip", version = "=1.9.17" }
solana-logger = { path = "../logger", version = "=1.9.17" }
solana-net-utils = { path = "../net-utils", version = "=1.9.17" }
solana-perf = { path = "../perf", version = "=1.9.17" }
solana-sdk = { path = "../sdk", version = "=1.9.17" }
solana-streamer = { path = "../streamer", version = "=1.9.17" }
solana-version = { path = "../version", version = "=1.9.17" }
solana-client = { path = "../client", version = "=1.9.17" }
=======
=======
clap = {version = "3.1.8", features = ["derive", "cargo"]}
log = "0.4.14"
>>>>>>> 0d773bd13 (chore: bump tokio-util from 0.6.9 to 0.7.1 (#213))
rand = "0.8.5"
serde = "1.0.136"
solana-client = { path = "../client", version = "=1.11.0" }
solana-core = { path = "../core", version = "=1.11.0" }
solana-gossip = { path = "../gossip", version = "=1.11.0" }
solana-logger = { path = "../logger", version = "=1.11.0" }
solana-net-utils = { path = "../net-utils", version = "=1.11.0" }
solana-perf = { path = "../perf", version = "=1.11.0" }
solana-sdk = { path = "../sdk", version = "=1.11.0" }
solana-streamer = { path = "../streamer", version = "=1.11.0" }
solana-version = { path = "../version", version = "=1.11.0" }
>>>>>>> 318544455 (chore: bump rand from 0.7.3 to 0.8.5 (#205))

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
