[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2021"
name = "solana-store-tool"
description = "Tool to inspect append vecs"
version = "1.9.17"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
publish = false

[dependencies]
<<<<<<< HEAD
=======
clap = "3.1.8"
>>>>>>> 9db7104e4 (chore: bump clap from 2.33.3 to 3.1.8 (#206))
log = { version = "0.4.14" }
solana-logger = { path = "../../logger", version = "=1.9.17" }
solana-version = { path = "../../version", version = "=1.9.17" }
solana-runtime = { path = "..", version = "=1.9.17" }
clap = "2.33.1"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
