[package]
name = "solana-metrics"
version = "1.9.17"
description = "Solana Metrics"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-metrics"
edition = "2021"

[dependencies]
env_logger = "0.9.0"
gethostname = "0.2.1"
lazy_static = "1.4.0"
log = "0.4.14"
reqwest = { version = "0.11.6", default-features = false, features = ["blocking", "rustls-tls", "json"] }
solana-sdk = { path = "../sdk", version = "=1.9.17" }

[dev-dependencies]
<<<<<<< HEAD
<<<<<<< HEAD
rand = "0.7.0"
serial_test = "0.5.1"
=======
=======
>>>>>>> 0d773bd13 (chore: bump tokio-util from 0.6.9 to 0.7.1 (#213))
env_logger = "0.9.0"
rand = "0.8.5"
serial_test = "0.6.0"
>>>>>>> 318544455 (chore: bump rand from 0.7.3 to 0.8.5 (#205))

[lib]
name = "solana_metrics"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
