[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2021"
name = "solana-bench-tps"
version = "1.9.17"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
publish = false

[dependencies]
<<<<<<< HEAD
<<<<<<< HEAD
clap = "2.33.1"
=======
clap = "3.1.8"
=======
clap = "3.1.10"
>>>>>>> e39c48ccd (chore: bump clap from 3.1.8 to 3.1.10 (#211))
crossbeam-channel = "0.5"
>>>>>>> 9db7104e4 (chore: bump clap from 2.33.3 to 3.1.8 (#206))
log = "0.4.14"
rayon = "1.5.1"
serde_json = "1.0.72"
serde_yaml = "0.8.21"
solana-core = { path = "../core", version = "=1.9.17" }
solana-genesis = { path = "../genesis", version = "=1.9.17" }
solana-client = { path = "../client", version = "=1.9.17" }
solana-faucet = { path = "../faucet", version = "=1.9.17" }
solana-gossip = { path = "../gossip", version = "=1.9.17" }
solana-logger = { path = "../logger", version = "=1.9.17" }
solana-metrics = { path = "../metrics", version = "=1.9.17" }
solana-measure = { path = "../measure", version = "=1.9.17" }
solana-net-utils = { path = "../net-utils", version = "=1.9.17" }
solana-runtime = { path = "../runtime", version = "=1.9.17" }
solana-sdk = { path = "../sdk", version = "=1.9.17" }
solana-streamer = { path = "../streamer", version = "=1.9.17" }
solana-version = { path = "../version", version = "=1.9.17" }

[dev-dependencies]
serial_test = "0.5.1"
solana-local-cluster = { path = "../local-cluster", version = "=1.9.17" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
